### ISSUE TITLE
Google On Device ML implementation in Asil Android

### ISSUE THREAD

**Issue by nizamuddin** [Kahf-Browser/Android#1]

**Comment by nizamuddin** [comment]
@asifddlks we can try on device ML https://developers.google.com/learn/topics/on-device-ml#on-device-ml-in-the-real-world .

Idea is we will try only Object detection part. If the object is human then we will send it to API otherwise we will show the images.

We need to observe the performance of the device.

**Comment by asifddlks** [comment]
TensorFlowLite Model

[final.zip](https://github.com/AsilHQ/Android/files/13805602/final.zip)

**Comment by asifddlks** [comment]
https://github.com/asifddlks/OnDeviceMLApplication
