### ISSUE TITLE
SafeGaze implementation on Asil Android

### ISSUE THREAD

**Issue by nizamuddin** [Kahf-Browser/Android#3]
- [ ] SafeGaze Api integration 
- [ ] SafeGaze On/Off feature implementation 
- [ ] SafeGaze Stats

**Comment by HMZahir** [comment]
https://www.figma.com/file/XrtzqVfC2W22lIA5LxyPSp/SafGaze-%26-Asil?type=design&node-id=2201-242&mode=design&t=3HPU0Edy9eFZLCeK-0
https://www.figma.com/file/XrtzqVfC2W22lIA5LxyPSp/SafGaze-%26-Asil?type=design&node-id=2432-37089&mode=design&t=3HPU0Edy9eFZLCeK-0

**Comment by HMZahir** [comment]
Turn off interface and Turn on interface

![Image](https://github.com/AsilHQ/Android/assets/89986591/ec61868d-37c4-489e-9afb-3cb378e05084)
