### ISSUE TITLE
Rebranding of Asil Android

### ISSUE THREAD

**Issue by nizamuddin** [Kahf-Browser/Android#4]
- [x] Replace asil URL(just replace duckduckgo.com with asil.co) in Learn more in web tracking protection
- [x] Replace asil URL (just replace duckduckgo.com with asil.co) in Learn more in global privacy control
- [x] Remove Email protection BETA
- [x] Rebrand Cookie Pop-up Protection  and also repalce asil.co link in the learnmore
- [x] Replace Learn more url in App Tracking protection and also need to replace one image in Who sees your data screen in the Enble process of App Tracking protection 
- [x] Rebrand settings -> about and also replace asil.co link in the help pages

**Comment by asifddlks** [comment]
[Disable Backup & Sync in settings](https://github.com/AsilHQ/Android/commit/4bd8391ab86a47567063f4c3fd894989791180db)

@denizgencay

**Comment by nizamuddin** [comment]
- [x] replace asil URL(just replace duckduckgo.com with asil.co) in Learn more in web tracking protection
- [x] replace asil URL (just replace duckduckgo.com with asil.co) in Learn more in global privacy control
@asifddlks @denizgencay

**Comment by asifddlks** [comment]
> * [x]  replace asil URL(just replace duckduckgo.com with asil.co) in Learn more in web tracking protection
> * [x]  replace asil URL (just replace duckduckgo.com with asil.co) in Learn more in global privacy control
>   @asifddlks @denizgencay

I will do both Insh'Allah.

**Comment by denizgencay** [comment]
> > * [x]   replace asil URL(just replace duckduckgo.com with asil.co) in Learn more in web tracking protection
> > * [x]   replace asil URL (just replace duckduckgo.com with asil.co) in Learn more in global privacy control
> >   @asifddlks @denizgencay
> 
> I will do both Insh'Allah.

Some requirements implemented please check the latest changes on first_release branch. @asifddlks

**Comment by asifddlks** [comment]
> > > * [ ]    replace asil URL(just replace duckduckgo.com with asil.co) in Learn more in web tracking protection
> > > * [ ]    replace asil URL (just replace duckduckgo.com with asil.co) in Learn more in global privacy control
> > >   @asifddlks @denizgencay
> > 
> > 
> > I will do both Insh'Allah.
> 
> Some requirements implemented please check the latest changes on first_release branch. @asifddlks

Okay. I will check.

**Comment by asifddlks** [comment]
> > > * [x]    replace asil URL(just replace duckduckgo.com with asil.co) in Learn more in web tracking protection
> > > * [x]    replace asil URL (just replace duckduckgo.com with asil.co) in Learn more in global privacy control
> > >   @asifddlks @denizgencay
> > 
> > 
> > I will do both Insh'Allah.
> 
> Some requirements implemented please check the latest changes on first_release branch. @asifddlks

Dear @denizgencay,
I have checked the branch "first_release". There you have removed the "Backup & Sync" from the settings menu.

Have you checked my commit on "feature/rebranding" [Backup & Sync in settings](https://github.com/AsilHQ/Android/commit/4bd8391ab86a47567063f4c3fd894989791180db) ?
I have already done the same resting the codes intact as we may need that feature in future.

Btw it will be great if we merge the rebranding branch into the first_release branch.
Will be waiting for your response brother.

**Comment by denizgencay** [comment]
@asifddlks I am merging branches.

**Comment by denizgencay** [comment]
I will get your changes related to the rebranding parts. @asifddlks

**Comment by asifddlks** [comment]
> I will get your changes related to the rebranding parts. @asifddlks

Sure brother. But we should maintain a "development" branch which will take the pull request in future.

**Comment by denizgencay** [comment]
Yes that's the plan, after initial launch we will go like that inshAllah @asifddlks

**Comment by asifddlks** [comment]
> Yes that's the plan, after initial launch we will go like that inshAllah @asifddlks

Insh'Allah. But it should be done anytime soon brother. Because we may face same issue again. My suggestion is then make the "first_release" branch to pull. Of course after taking the commits from the "feature/rebranding"

**Comment by denizgencay** [comment]
@asifddlks I merged the branches could you please check if anything is missing or is there any problem I couldn't see anything, if you approve I will merge it to development for achieving reliable development.

**Comment by asifddlks** [comment]
> @asifddlks I merged the branches could you please check if anything is missing or is there any problem I couldn't see anything, if you approve I will merge it to development for achieving reliable development.

@denizgencay which branch did u merge into?
I will check tomorrow Insh'Allah.

**Comment by denizgencay** [comment]
@asifddlks Nizam approved last commit merging everything in develop.

**Comment by denizgencay** [comment]
@asifddlks Merged everything to develop branch after that I merged develop to master because we gave a release. Lastly created a new release branch named 1.1.5. Lets create our new branches from develop. We are not touching main branch for sync fork action.

**Comment by asifddlks** [comment]
> @asifddlks Merged everything to develop branch after that I merged develop to master because we gave a release. Lastly created a new release branch named 1.1.5. Lets create our new branches from develop. We are not touching main branch for sync fork action.

Great brother.

**Comment by asifddlks** [comment]
@denizgencay There was a deprecated dependency issue in dagger which causes build error whenever I tried to change the VpnOnboardingActivity. You will find the change in this commit.

[Fix build issue for deprecated dagger library](https://github.com/AsilHQ/Android/commit/1c54bdf8c6f4a234ba51f629dffc22c065c7a347)

**Comment by denizgencay** [comment]
@asifddlks Which feature needs work on that Activity and thank you for notifying

**Comment by denizgencay** [comment]
@asifddlks  private const val FAQ_WEBSITE = "https://help.duckduckgo.com/duckduckgo-help-pages/p-app-tracking-protection/what-is-app-tracking-protection/"

I have cherry-picked the changes only this line is causing the problem.

**Comment by asifddlks** [comment]
> @asifddlks private const val FAQ_WEBSITE = "https://help.duckduckgo.com/duckduckgo-help-pages/p-app-tracking-protection/what-is-app-tracking-protection/"
> 
> I have cherry-picked the changes only this line is causing the problem.

This from "VpnOnboardingActivity" right?

**Comment by denizgencay** [comment]
@asifddlks  Sorry yes.

**Comment by denizgencay** [comment]
@asifddlks I am merging other changes.

**Comment by denizgencay** [comment]
@asifddlks Could you check searching on your side? I have faced an issue: when I search for something, the browser immediately redirects me to Asil's website.

**Comment by denizgencay** [comment]
@asifddlks As you know I can't build your branch because of that I can't control it I was working on my branch for another feature and that branch doesn't include your changes. My branch works fine today I merged my branch with development and tried it on development it's not working could you please check that?

**Comment by asifddlks** [comment]
> @asifddlks Could you check searching on your side? I have faced an issue: when I search for something, the browser immediately redirects me to Asil's website.

It seems okay on my side (the one which I build last time on my device).

**Comment by denizgencay** [comment]
@asifddlks Can you check development branch suggestions working? Only safe_gaze_counter working on my side. I am typing for example halktv it's redirecting me to Asil.co

**Comment by asifddlks** [comment]
> @asifddlks As you know I can't build your branch because of that I can't control it I was working on my branch for another feature and that branch doesn't include your changes. My branch works fine today I merged my branch with development and tried it on development it's not working could you please check that?

You mentioned that you have cherry picked the changes except "VpnOnboardingActivity" FAQ url.
I haven't pushed anything on development branch. 

As I'm currently outside of my workstation, I can check it on Monday.

**Comment by asifddlks** [comment]
> @asifddlks Can you check development branch suggestions working? Only safe_gaze_counter working on my side. I am typing for example halktv it's redirecting me to Asil.co

I will brother. But I can do it on Monday Insh'Allah.

**Comment by denizgencay** [comment]
@asifddlks Thank you brother I will check too if I can solve it I will let you know.
