### ISSUE TITLE
KahfTube implementation on Asil Android

### ISSUE THREAD

**Issue by nizamuddin** [Kahf-Browser/Android#9]
We categorised huge number of channels and videos . 
Categorized as 
1. Not permitted for Muslims 
2. Permitted for Women 
3. Permitted for men 
4. Permitted for Children
Based on Islamic views 
1. Liberal
2. Moderate
3. Practicing 

What you need to do when someone browse [YouTube.com](http://m.youtube.com/)

- [x] 1. Unsubscribe the non permitted channels
- [x] 2. Replace the div of non-permitted (Haram)videos on the homepage, search page, and other pages with Halal videos
- [x] 3. Show message in the single not permitted video link if they go directly
- [x] 4. Able to switch Men, women, and children mode
- [x] 5. Able to switch conservative, moderate, and extreme mode
- [x] 6. Collect email from YouTube profile and auto login then in Halalz without password

API docs: https://kahfhq.github.io/api-docs/ (please ignore the api end point api.halalz.co, please try with https://api.kahf.ai/api/v1)
Please follow the app and implement exact features 
Android app: https://play.google.com/store/apps/details?id=com.halalz.kahftube

iOS version: https://apps.apple.com/tr/app/kahf-tube/id6446837508

**Comment by nizamuddin** [comment]
here is Postman collection 

[Halalz.postman_collection.json](https://github.com/AsilHQ/Android/files/13942284/Halalz.postman_collection.json)

**Comment by asifddlks** [comment]
https://github.com/halalz/halalz-tube-app

**Comment by asifddlks** [comment]
- [x] Check if user signed in or not if yes get user information (name, email, image)
- [x] Register/Login with user information to https://api.kahf.ai/api/v1/ and get user token 
- [x] Store user information, user preference and token in DataStore
- [x] Make ui and functionality for user profile and preference
- [x] Inject main javascript file to check halal or haram YouTube videos
- [x] Implement unsubscribe feature using existing javascript
- [x] Integrate KahfTube into Asil Browser
- [x] Login prompt for Kahftube in Asil Browser
- [x] Fix desktop mode/site issue in kahftube unsubscribe
